{
//=========Macro generated from canvas: MyC/MyC
//=========  (Mon Dec  5 11:13:45 2016) by ROOT version5.34/07
   TCanvas *MyC = new TCanvas("MyC", "MyC",13,36,700,500);
   gStyle->SetOptFit(1);
   MyC->Range(63.51351,-0.2799421,266.2162,0.9431255);
   MyC->SetFillColor(0);
   MyC->SetBorderMode(0);
   MyC->SetBorderSize(2);
   MyC->SetLeftMargin(0.18);
   MyC->SetRightMargin(0.08);
   MyC->SetTopMargin(0.07);
   MyC->SetBottomMargin(0.17);
   MyC->SetFrameLineWidth(3);
   MyC->SetFrameBorderMode(0);
   MyC->SetFrameBorderSize(0);
   MyC->SetFrameLineWidth(3);
   MyC->SetFrameBorderMode(0);
   MyC->SetFrameBorderSize(0);
   
   TH1F *minDPhiPassCR1 = new TH1F("minDPhiPassCR1","minDPhiPassCR1",3,100,250);
   minDPhiPassCR1->SetBinContent(1,0.5);
   minDPhiPassCR1->SetBinContent(2,0.35);
   minDPhiPassCR1->SetBinContent(3,0.1);
   minDPhiPassCR1->SetBinError(1,0.18);
   minDPhiPassCR1->SetBinError(2,0.08);
   minDPhiPassCR1->SetBinError(3,0.1);
   minDPhiPassCR1->SetMinimum(-0.07202062);
   minDPhiPassCR1->SetMaximum(0.8575108);
   minDPhiPassCR1->SetEntries(18.49385);
   
   TPaveStats *ptstats = new TPaveStats(0.9511494,0.9533898,0.9798851,0.9957627,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(0);
   ptstats->SetFillColor(0);
   ptstats->SetLineColor(0);
   ptstats->SetLineWidth(2);
   ptstats->SetTextAlign(12);
   ptstats->SetTextColor(0);
   TText *text = ptstats->AddText("minDPhiPassCR1");
   text->SetTextSize(0.009745763);
   text = ptstats->AddText("Entries = 18     ");
   text = ptstats->AddText("Mean  =  153.9");
   text = ptstats->AddText("RMS   =   33.7");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(73);
   ptstats->Draw();
   minDPhiPassCR1->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(minDPhiPassCR1);
   minDPhiPassCR1->SetLineColor(4);
   minDPhiPassCR1->SetLineWidth(2);
   minDPhiPassCR1->GetXaxis()->SetTitle("#Sigma M_{T}^{#tau_{i}} (GeV)");
   minDPhiPassCR1->GetXaxis()->SetNdivisions(505);
   minDPhiPassCR1->GetXaxis()->SetLabelFont(42);
   minDPhiPassCR1->GetXaxis()->SetLabelSize(0.07);
   minDPhiPassCR1->GetXaxis()->SetTitleSize(0.07);
   minDPhiPassCR1->GetXaxis()->SetTitleOffset(1.1);
   minDPhiPassCR1->GetXaxis()->SetTitleFont(42);
   minDPhiPassCR1->GetYaxis()->SetTitle("#Delta#phi efficiency");
   minDPhiPassCR1->GetYaxis()->SetNdivisions(505);
   minDPhiPassCR1->GetYaxis()->SetLabelFont(42);
   minDPhiPassCR1->GetYaxis()->SetLabelSize(0.07);
   minDPhiPassCR1->GetYaxis()->SetTitleSize(0.07);
   minDPhiPassCR1->GetYaxis()->SetTitleOffset(1.3);
   minDPhiPassCR1->GetYaxis()->SetTitleFont(42);
   minDPhiPassCR1->GetZaxis()->SetLabelFont(42);
   minDPhiPassCR1->GetZaxis()->SetLabelSize(0.035);
   minDPhiPassCR1->GetZaxis()->SetTitleSize(0.035);
   minDPhiPassCR1->GetZaxis()->SetTitleFont(42);
   minDPhiPassCR1->Draw("E1");
   
   TH1F *minDPhiPassCR2 = new TH1F("minDPhiPassCR2","minDPhiPassCR2",3,100,250);
   minDPhiPassCR2->SetBinContent(1,0.59);
   minDPhiPassCR2->SetBinContent(2,0.31);
   minDPhiPassCR2->SetBinContent(3,0.2);
   minDPhiPassCR2->SetBinError(1,0.21);
   minDPhiPassCR2->SetBinError(2,0.075);
   minDPhiPassCR2->SetBinError(3,0.13);
   minDPhiPassCR2->SetMinimum(-0.07202062);
   minDPhiPassCR2->SetMaximum(0.8575108);
   minDPhiPassCR2->SetEntries(18.16135);
   minDPhiPassCR2->SetLineStyle(5);
   minDPhiPassCR2->SetLineWidth(2);
   minDPhiPassCR2->GetXaxis()->SetNdivisions(505);
   minDPhiPassCR2->GetXaxis()->SetLabelFont(42);
   minDPhiPassCR2->GetXaxis()->SetLabelSize(0.07);
   minDPhiPassCR2->GetXaxis()->SetTitleSize(0.07);
   minDPhiPassCR2->GetXaxis()->SetTitleOffset(1.1);
   minDPhiPassCR2->GetXaxis()->SetTitleFont(42);
   minDPhiPassCR2->GetYaxis()->SetNdivisions(505);
   minDPhiPassCR2->GetYaxis()->SetLabelFont(42);
   minDPhiPassCR2->GetYaxis()->SetLabelSize(0.07);
   minDPhiPassCR2->GetYaxis()->SetTitleSize(0.07);
   minDPhiPassCR2->GetYaxis()->SetTitleOffset(1.3);
   minDPhiPassCR2->GetYaxis()->SetTitleFont(42);
   minDPhiPassCR2->GetZaxis()->SetLabelFont(42);
   minDPhiPassCR2->GetZaxis()->SetLabelSize(0.035);
   minDPhiPassCR2->GetZaxis()->SetTitleSize(0.035);
   minDPhiPassCR2->GetZaxis()->SetTitleFont(42);
   minDPhiPassCR2->Draw("E1same");
   
   TH1F *minDPhiPass = new TH1F("minDPhiPass","minDPhiPassCR1",3,100,250);
   minDPhiPass->SetBinContent(1,0.5409091);
   minDPhiPass->SetBinContent(2,0.3318182);
   minDPhiPass->SetBinContent(3,0.1454545);
   minDPhiPass->SetBinError(1,0.1369352);
   minDPhiPass->SetBinError(2,0.05537438);
   minDPhiPass->SetBinError(3,0.0804173);
   minDPhiPass->SetMinimum(-0.07202062);
   minDPhiPass->SetMaximum(0.8575108);
   minDPhiPass->SetEntries(36.65238);
   minDPhiPass->SetLineColor(2);
   minDPhiPass->SetLineStyle(2);
   minDPhiPass->SetLineWidth(3);
   minDPhiPass->GetXaxis()->SetNdivisions(505);
   minDPhiPass->GetXaxis()->SetLabelFont(42);
   minDPhiPass->GetXaxis()->SetLabelSize(0.07);
   minDPhiPass->GetXaxis()->SetTitleSize(0.07);
   minDPhiPass->GetXaxis()->SetTitleOffset(1.1);
   minDPhiPass->GetXaxis()->SetTitleFont(42);
   minDPhiPass->GetYaxis()->SetNdivisions(505);
   minDPhiPass->GetYaxis()->SetLabelFont(42);
   minDPhiPass->GetYaxis()->SetLabelSize(0.07);
   minDPhiPass->GetYaxis()->SetTitleSize(0.07);
   minDPhiPass->GetYaxis()->SetTitleOffset(1.3);
   minDPhiPass->GetYaxis()->SetTitleFont(42);
   minDPhiPass->GetZaxis()->SetLabelFont(42);
   minDPhiPass->GetZaxis()->SetLabelSize(0.035);
   minDPhiPass->GetZaxis()->SetTitleSize(0.035);
   minDPhiPass->GetZaxis()->SetTitleFont(42);
   minDPhiPass->Draw("same");
   
   TLegend *leg = new TLegend(0.5,0.6716102,0.8793103,0.8813559,NULL,"brNDC");
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(2);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("minDPhiPassCR1","CR1","lpf");
   entry->SetFillStyle(1001);
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("minDPhiPassCR2","CR2","lpf");
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(5);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("minDPhiPass","CR1 + CR2","lpf");
   entry->SetFillStyle(1001);
   entry->SetLineColor(2);
   entry->SetLineStyle(2);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   leg->Draw();
      tex = new TLatex(0.6845638,0.9423077,"18.1 fb^{-1} (8 TeV)");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.03671329);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.3271812,0.4083916,"CMS");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.335,0.3541958,"#tau_{h}#tau_{h}");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TPaveText *pt = new TPaveText(0.00862069,0.9533898,0.03735632,0.9957627,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetLineColor(0);
   pt->SetLineWidth(2);
   pt->SetTextColor(0);
   text = pt->AddText("minDPhiPassCR1");
   pt->Draw();
   MyC->Modified();
   MyC->cd();
   MyC->SetSelected(MyC);
}
