{
//=========Macro generated from canvas: MT2_ratioc_ratio/
//=========  (Tue Nov 26 10:41:52 2013) by ROOT version5.32/00
   TCanvas *MT2_ratioc_ratio = new TCanvas("MT2_ratioc_ratio", "",1,52,600,630);
   gStyle->SetOptFit(1);
   MT2_ratioc_ratio->Range(0,0,1,1);
   MT2_ratioc_ratio->SetFillColor(0);
   MT2_ratioc_ratio->SetBorderMode(0);
   MT2_ratioc_ratio->SetBorderSize(2);
   MT2_ratioc_ratio->SetLeftMargin(0.18);
   MT2_ratioc_ratio->SetRightMargin(0.08);
   MT2_ratioc_ratio->SetTopMargin(0.07);
   MT2_ratioc_ratio->SetBottomMargin(0.17);
   MT2_ratioc_ratio->SetFrameBorderMode(0);
   MT2_ratioc_ratio->SetFrameBorderSize(0);
  
// ------------>Primitives in pad: MT2_ratio_plotpad
   TPad *MT2_ratio_plotpad = new TPad("MT2_ratio_plotpad", "Pad containing the overlay plot",0,0.211838,1,1);
   MT2_ratio_plotpad->Draw();
   MT2_ratio_plotpad->cd();
   MT2_ratio_plotpad->Range(-0.667557,-2.859879,4.405874,5.018491);
   MT2_ratio_plotpad->SetFillColor(0);
   MT2_ratio_plotpad->SetFillStyle(4000);
   MT2_ratio_plotpad->SetBorderMode(0);
   MT2_ratio_plotpad->SetBorderSize(2);
   MT2_ratio_plotpad->SetLogy();
   MT2_ratio_plotpad->SetLeftMargin(0.131579);
   MT2_ratio_plotpad->SetRightMargin(0.08);
   MT2_ratio_plotpad->SetTopMargin(0.06895515);
   MT2_ratio_plotpad->SetBottomMargin(0.07206074);
   MT2_ratio_plotpad->SetFrameLineWidth(3);
   MT2_ratio_plotpad->SetFrameBorderMode(0);
   MT2_ratio_plotpad->SetFrameBorderSize(0);
   MT2_ratio_plotpad->SetFrameLineWidth(3);
   MT2_ratio_plotpad->SetFrameBorderMode(0);
   MT2_ratio_plotpad->SetFrameBorderSize(0);
   
   THStack *NBJetsCSVT = new THStack();
   NBJetsCSVT->SetName("NBJetsCSVT");
   NBJetsCSVT->SetTitle("");
   NBJetsCSVT->SetMinimum(0.02);
   NBJetsCSVT->SetMaximum(13780);
   
   TH1F *NBJetsCSVT_stack_1 = new TH1F("NBJetsCSVT_stack_1","",4,0,4);
   NBJetsCSVT_stack_1->SetMinimum(0.0051032);
   NBJetsCSVT_stack_1->SetMaximum(29870.13);
   NBJetsCSVT_stack_1->SetDirectory(0);
   NBJetsCSVT_stack_1->SetStats(0);
   NBJetsCSVT_stack_1->SetLineWidth(2);
   NBJetsCSVT_stack_1->GetXaxis()->SetTitle("NBJetsCSVT");
   NBJetsCSVT_stack_1->GetXaxis()->SetNdivisions(505);
   NBJetsCSVT_stack_1->GetXaxis()->SetLabelFont(42);
   NBJetsCSVT_stack_1->GetXaxis()->SetLabelSize(0.05);
   NBJetsCSVT_stack_1->GetXaxis()->SetTitleSize(0.05);
   NBJetsCSVT_stack_1->GetXaxis()->SetTitleOffset(1.1);
   NBJetsCSVT_stack_1->GetXaxis()->SetTitleFont(42);
   NBJetsCSVT_stack_1->GetYaxis()->SetTitle("Events");
   NBJetsCSVT_stack_1->GetYaxis()->SetNdivisions(505);
   NBJetsCSVT_stack_1->GetYaxis()->SetLabelFont(42);
   NBJetsCSVT_stack_1->GetYaxis()->SetLabelSize(0.05);
   NBJetsCSVT_stack_1->GetYaxis()->SetTitleSize(0.05);
   NBJetsCSVT_stack_1->GetYaxis()->SetTitleOffset(1.3);
   NBJetsCSVT_stack_1->GetYaxis()->SetTitleFont(42);
   NBJetsCSVT_stack_1->GetZaxis()->SetLabelFont(42);
   NBJetsCSVT_stack_1->GetZaxis()->SetLabelSize(0.035);
   NBJetsCSVT_stack_1->GetZaxis()->SetTitleSize(0.035);
   NBJetsCSVT_stack_1->GetZaxis()->SetTitleFont(42);
   NBJetsCSVT->SetHistogram(NBJetsCSVT_stack_1);
   
   
   TH1F *NBJetsCSVT_QCD = new TH1F("NBJetsCSVT_QCD","",4,0,4);
   NBJetsCSVT_QCD->SetBinContent(1,688.1085);
   NBJetsCSVT_QCD->SetBinContent(2,111.7087);
   NBJetsCSVT_QCD->SetBinContent(3,13.89926);
   NBJetsCSVT_QCD->SetBinContent(4,0.00914911);
   NBJetsCSVT_QCD->SetBinError(1,121.4384);
   NBJetsCSVT_QCD->SetBinError(2,41.11963);
   NBJetsCSVT_QCD->SetBinError(3,4.843125);
   NBJetsCSVT_QCD->SetBinError(4,0.008725277);
   NBJetsCSVT_QCD->SetEntries(1634);
   NBJetsCSVT_QCD->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#cccc00");
   NBJetsCSVT_QCD->SetFillColor(ci);

   ci = TColor::GetColor("#cccc00");
   NBJetsCSVT_QCD->SetLineColor(ci);
   NBJetsCSVT_QCD->SetLineWidth(2);

   ci = TColor::GetColor("#cccc00");
   NBJetsCSVT_QCD->SetMarkerColor(ci);
   NBJetsCSVT_QCD->GetXaxis()->SetNdivisions(505);
   NBJetsCSVT_QCD->GetXaxis()->SetLabelFont(42);
   NBJetsCSVT_QCD->GetXaxis()->SetLabelSize(0.07);
   NBJetsCSVT_QCD->GetXaxis()->SetTitleSize(0.07);
   NBJetsCSVT_QCD->GetXaxis()->SetTitleOffset(1.1);
   NBJetsCSVT_QCD->GetXaxis()->SetTitleFont(42);
   NBJetsCSVT_QCD->GetYaxis()->SetNdivisions(505);
   NBJetsCSVT_QCD->GetYaxis()->SetLabelFont(42);
   NBJetsCSVT_QCD->GetYaxis()->SetLabelSize(0.07);
   NBJetsCSVT_QCD->GetYaxis()->SetTitleSize(0.07);
   NBJetsCSVT_QCD->GetYaxis()->SetTitleOffset(1.3);
   NBJetsCSVT_QCD->GetYaxis()->SetTitleFont(42);
   NBJetsCSVT_QCD->GetZaxis()->SetLabelFont(42);
   NBJetsCSVT_QCD->GetZaxis()->SetLabelSize(0.035);
   NBJetsCSVT_QCD->GetZaxis()->SetTitleSize(0.035);
   NBJetsCSVT_QCD->GetZaxis()->SetTitleFont(42);
   NBJetsCSVT->Add(NBJetsCSVT_QCD,"");
   
   TH1F *NBJetsCSVT_Wjets = new TH1F("NBJetsCSVT_Wjets","",4,0,4);
   NBJetsCSVT_Wjets->SetBinContent(1,702.0617);
   NBJetsCSVT_Wjets->SetBinContent(2,44.60124);
   NBJetsCSVT_Wjets->SetBinContent(3,7.456479);
   NBJetsCSVT_Wjets->SetBinError(1,13.52188);
   NBJetsCSVT_Wjets->SetBinError(2,3.42414);
   NBJetsCSVT_Wjets->SetBinError(3,1.385031);
   NBJetsCSVT_Wjets->SetEntries(2966);
   NBJetsCSVT_Wjets->SetStats(0);

   ci = TColor::GetColor("#00cc00");
   NBJetsCSVT_Wjets->SetFillColor(ci);

   ci = TColor::GetColor("#00cc00");
   NBJetsCSVT_Wjets->SetLineColor(ci);
   NBJetsCSVT_Wjets->SetLineWidth(2);

   ci = TColor::GetColor("#00cc00");
   NBJetsCSVT_Wjets->SetMarkerColor(ci);
   NBJetsCSVT_Wjets->GetXaxis()->SetNdivisions(505);
   NBJetsCSVT_Wjets->GetXaxis()->SetLabelFont(42);
   NBJetsCSVT_Wjets->GetXaxis()->SetLabelSize(0.07);
   NBJetsCSVT_Wjets->GetXaxis()->SetTitleSize(0.07);
   NBJetsCSVT_Wjets->GetXaxis()->SetTitleOffset(1.1);
   NBJetsCSVT_Wjets->GetXaxis()->SetTitleFont(42);
   NBJetsCSVT_Wjets->GetYaxis()->SetNdivisions(505);
   NBJetsCSVT_Wjets->GetYaxis()->SetLabelFont(42);
   NBJetsCSVT_Wjets->GetYaxis()->SetLabelSize(0.07);
   NBJetsCSVT_Wjets->GetYaxis()->SetTitleSize(0.07);
   NBJetsCSVT_Wjets->GetYaxis()->SetTitleOffset(1.3);
   NBJetsCSVT_Wjets->GetYaxis()->SetTitleFont(42);
   NBJetsCSVT_Wjets->GetZaxis()->SetLabelFont(42);
   NBJetsCSVT_Wjets->GetZaxis()->SetLabelSize(0.035);
   NBJetsCSVT_Wjets->GetZaxis()->SetTitleSize(0.035);
   NBJetsCSVT_Wjets->GetZaxis()->SetTitleFont(42);
   NBJetsCSVT->Add(NBJetsCSVT_Wjets,"");
   
   TH1F *NBJetsCSVT_Zjets = new TH1F("NBJetsCSVT_Zjets","",4,0,4);
   NBJetsCSVT_Zjets->SetBinContent(1,506.2357);
   NBJetsCSVT_Zjets->SetBinContent(2,37.63772);
   NBJetsCSVT_Zjets->SetBinContent(3,7.571334);
   NBJetsCSVT_Zjets->SetBinContent(4,0.202371);
   NBJetsCSVT_Zjets->SetBinError(1,5.84405);
   NBJetsCSVT_Zjets->SetBinError(2,1.004419);
   NBJetsCSVT_Zjets->SetBinError(3,0.4592181);
   NBJetsCSVT_Zjets->SetBinError(4,0.06745701);
   NBJetsCSVT_Zjets->SetEntries(23399);
   NBJetsCSVT_Zjets->SetStats(0);

   ci = TColor::GetColor("#006600");
   NBJetsCSVT_Zjets->SetFillColor(ci);

   ci = TColor::GetColor("#006600");
   NBJetsCSVT_Zjets->SetLineColor(ci);
   NBJetsCSVT_Zjets->SetLineWidth(2);

   ci = TColor::GetColor("#006600");
   NBJetsCSVT_Zjets->SetMarkerColor(ci);
   NBJetsCSVT_Zjets->GetXaxis()->SetNdivisions(505);
   NBJetsCSVT_Zjets->GetXaxis()->SetLabelFont(42);
   NBJetsCSVT_Zjets->GetXaxis()->SetLabelSize(0.07);
   NBJetsCSVT_Zjets->GetXaxis()->SetTitleSize(0.07);
   NBJetsCSVT_Zjets->GetXaxis()->SetTitleOffset(1.1);
   NBJetsCSVT_Zjets->GetXaxis()->SetTitleFont(42);
   NBJetsCSVT_Zjets->GetYaxis()->SetNdivisions(505);
   NBJetsCSVT_Zjets->GetYaxis()->SetLabelFont(42);
   NBJetsCSVT_Zjets->GetYaxis()->SetLabelSize(0.07);
   NBJetsCSVT_Zjets->GetYaxis()->SetTitleSize(0.07);
   NBJetsCSVT_Zjets->GetYaxis()->SetTitleOffset(1.3);
   NBJetsCSVT_Zjets->GetYaxis()->SetTitleFont(42);
   NBJetsCSVT_Zjets->GetZaxis()->SetLabelFont(42);
   NBJetsCSVT_Zjets->GetZaxis()->SetLabelSize(0.035);
   NBJetsCSVT_Zjets->GetZaxis()->SetTitleSize(0.035);
   NBJetsCSVT_Zjets->GetZaxis()->SetTitleFont(42);
   NBJetsCSVT->Add(NBJetsCSVT_Zjets,"");
   
   TH1F *NBJetsCSVT_Top = new TH1F("NBJetsCSVT_Top","",4,0,4);
   NBJetsCSVT_Top->SetBinContent(1,460.0576);
   NBJetsCSVT_Top->SetBinContent(2,719.19);
   NBJetsCSVT_Top->SetBinContent(3,292.7933);
   NBJetsCSVT_Top->SetBinContent(4,18.49689);
   NBJetsCSVT_Top->SetBinError(1,16.29545);
   NBJetsCSVT_Top->SetBinError(2,20.4313);
   NBJetsCSVT_Top->SetBinError(3,13.04363);
   NBJetsCSVT_Top->SetBinError(4,3.283264);
   NBJetsCSVT_Top->SetBinError(5,1.024639);
   NBJetsCSVT_Top->SetEntries(2613);
   NBJetsCSVT_Top->SetStats(0);

   ci = TColor::GetColor("#3366cc");
   NBJetsCSVT_Top->SetFillColor(ci);

   ci = TColor::GetColor("#3366cc");
   NBJetsCSVT_Top->SetLineColor(ci);
   NBJetsCSVT_Top->SetLineWidth(2);

   ci = TColor::GetColor("#3366cc");
   NBJetsCSVT_Top->SetMarkerColor(ci);
   NBJetsCSVT_Top->GetXaxis()->SetNdivisions(505);
   NBJetsCSVT_Top->GetXaxis()->SetLabelFont(42);
   NBJetsCSVT_Top->GetXaxis()->SetLabelSize(0.07);
   NBJetsCSVT_Top->GetXaxis()->SetTitleSize(0.07);
   NBJetsCSVT_Top->GetXaxis()->SetTitleOffset(1.1);
   NBJetsCSVT_Top->GetXaxis()->SetTitleFont(42);
   NBJetsCSVT_Top->GetYaxis()->SetNdivisions(505);
   NBJetsCSVT_Top->GetYaxis()->SetLabelFont(42);
   NBJetsCSVT_Top->GetYaxis()->SetLabelSize(0.07);
   NBJetsCSVT_Top->GetYaxis()->SetTitleSize(0.07);
   NBJetsCSVT_Top->GetYaxis()->SetTitleOffset(1.3);
   NBJetsCSVT_Top->GetYaxis()->SetTitleFont(42);
   NBJetsCSVT_Top->GetZaxis()->SetLabelFont(42);
   NBJetsCSVT_Top->GetZaxis()->SetLabelSize(0.035);
   NBJetsCSVT_Top->GetZaxis()->SetTitleSize(0.035);
   NBJetsCSVT_Top->GetZaxis()->SetTitleFont(42);
   NBJetsCSVT->Add(NBJetsCSVT_Top,"");
   NBJetsCSVT->Draw("hist");
   
   TH1F *h2_copy = new TH1F("h2_copy","",4,0,4);
   h2_copy->SetBinContent(1,2756);
   h2_copy->SetBinContent(2,1008);
   h2_copy->SetBinContent(3,291);
   h2_copy->SetBinContent(4,25);
   h2_copy->SetBinError(1,52.49762);
   h2_copy->SetBinError(2,31.74902);
   h2_copy->SetBinError(3,17.05872);
   h2_copy->SetBinError(4,5);
   h2_copy->SetBinError(5,1.732051);
   h2_copy->SetMinimum(0.05);
   h2_copy->SetMaximum(13780);
   h2_copy->SetEntries(4084);
   h2_copy->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   h2_copy->SetFillColor(ci);
   h2_copy->SetLineWidth(2);
   h2_copy->SetMarkerStyle(20);
   h2_copy->GetXaxis()->SetNdivisions(505);
   h2_copy->GetXaxis()->SetLabelFont(42);
   h2_copy->GetXaxis()->SetLabelSize(0.07);
   h2_copy->GetXaxis()->SetTitleSize(0.07);
   h2_copy->GetXaxis()->SetTitleOffset(1.1);
   h2_copy->GetXaxis()->SetTitleFont(42);
   h2_copy->GetYaxis()->SetNdivisions(505);
   h2_copy->GetYaxis()->SetLabelFont(42);
   h2_copy->GetYaxis()->SetLabelSize(0.07);
   h2_copy->GetYaxis()->SetTitleSize(0.07);
   h2_copy->GetYaxis()->SetTitleOffset(1.3);
   h2_copy->GetYaxis()->SetTitleFont(42);
   h2_copy->GetZaxis()->SetLabelFont(42);
   h2_copy->GetZaxis()->SetLabelSize(0.035);
   h2_copy->GetZaxis()->SetTitleSize(0.035);
   h2_copy->GetZaxis()->SetTitleFont(42);
   h2_copy->Draw("sameE");
   
   TH1F *NBJetsCSVT_SMS = new TH1F("NBJetsCSVT_SMS","",4,0,4);
   NBJetsCSVT_SMS->SetBinContent(1,100.9609);
   NBJetsCSVT_SMS->SetBinContent(2,182.956);
   NBJetsCSVT_SMS->SetBinContent(3,88.9028);
   NBJetsCSVT_SMS->SetBinContent(4,6.467652);
   NBJetsCSVT_SMS->SetBinError(1,3.326785);
   NBJetsCSVT_SMS->SetBinError(2,4.478402);
   NBJetsCSVT_SMS->SetBinError(3,3.121802);
   NBJetsCSVT_SMS->SetBinError(4,0.842017);
   NBJetsCSVT_SMS->SetBinError(5,0.2685162);
   NBJetsCSVT_SMS->SetEntries(3464);
   NBJetsCSVT_SMS->SetStats(0);
   NBJetsCSVT_SMS->SetLineStyle(3);
   NBJetsCSVT_SMS->SetLineWidth(4);
   NBJetsCSVT_SMS->SetMarkerColor(0);
   NBJetsCSVT_SMS->GetXaxis()->SetNdivisions(505);
   NBJetsCSVT_SMS->GetXaxis()->SetLabelFont(42);
   NBJetsCSVT_SMS->GetXaxis()->SetLabelSize(0.07);
   NBJetsCSVT_SMS->GetXaxis()->SetTitleSize(0.07);
   NBJetsCSVT_SMS->GetXaxis()->SetTitleOffset(1.1);
   NBJetsCSVT_SMS->GetXaxis()->SetTitleFont(42);
   NBJetsCSVT_SMS->GetYaxis()->SetNdivisions(505);
   NBJetsCSVT_SMS->GetYaxis()->SetLabelFont(42);
   NBJetsCSVT_SMS->GetYaxis()->SetLabelSize(0.07);
   NBJetsCSVT_SMS->GetYaxis()->SetTitleSize(0.07);
   NBJetsCSVT_SMS->GetYaxis()->SetTitleOffset(1.3);
   NBJetsCSVT_SMS->GetYaxis()->SetTitleFont(42);
   NBJetsCSVT_SMS->GetZaxis()->SetLabelFont(42);
   NBJetsCSVT_SMS->GetZaxis()->SetLabelSize(0.035);
   NBJetsCSVT_SMS->GetZaxis()->SetTitleSize(0.035);
   NBJetsCSVT_SMS->GetZaxis()->SetTitleFont(42);
   NBJetsCSVT_SMS->Draw("samehist");
   TLatex *   tex = new TLatex(0.13,0.943,"#geq 4 jets");
tex->SetNDC();
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.68,0.943,"#sqrt{s} = 8 TeV, L = 17.43 fb^{-1}");
tex->SetNDC();
   tex->SetTextSize(0.0305);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH1F *NBJetsCSVT__1 = new TH1F("NBJetsCSVT__1","",4,0,4);
   NBJetsCSVT__1->SetMinimum(0.0051032);
   NBJetsCSVT__1->SetMaximum(29870.13);
   NBJetsCSVT__1->SetDirectory(0);
   NBJetsCSVT__1->SetStats(0);
   NBJetsCSVT__1->SetLineWidth(2);
   NBJetsCSVT__1->GetXaxis()->SetTitle("NBJetsCSVT");
   NBJetsCSVT__1->GetXaxis()->SetNdivisions(505);
   NBJetsCSVT__1->GetXaxis()->SetLabelFont(42);
   NBJetsCSVT__1->GetXaxis()->SetLabelSize(0.05);
   NBJetsCSVT__1->GetXaxis()->SetTitleSize(0.05);
   NBJetsCSVT__1->GetXaxis()->SetTitleOffset(1.1);
   NBJetsCSVT__1->GetXaxis()->SetTitleFont(42);
   NBJetsCSVT__1->GetYaxis()->SetTitle("Events");
   NBJetsCSVT__1->GetYaxis()->SetNdivisions(505);
   NBJetsCSVT__1->GetYaxis()->SetLabelFont(42);
   NBJetsCSVT__1->GetYaxis()->SetLabelSize(0.05);
   NBJetsCSVT__1->GetYaxis()->SetTitleSize(0.05);
   NBJetsCSVT__1->GetYaxis()->SetTitleOffset(1.3);
   NBJetsCSVT__1->GetYaxis()->SetTitleFont(42);
   NBJetsCSVT__1->GetZaxis()->SetLabelFont(42);
   NBJetsCSVT__1->GetZaxis()->SetLabelSize(0.035);
   NBJetsCSVT__1->GetZaxis()->SetTitleSize(0.035);
   NBJetsCSVT__1->GetZaxis()->SetTitleFont(42);
   NBJetsCSVT__1->Draw("sameaxis");
   
   TLegend *leg = new TLegend(0.7281879,0.5563725,0.909396,0.920147,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(2);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("NBJetsCSVT_QCD","QCD","f");

   ci = TColor::GetColor("#cccc00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#cccc00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("NBJetsCSVT_Wjets","W+jets","f");

   ci = TColor::GetColor("#00cc00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00cc00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("NBJetsCSVT_Zjets","Z+jets","f");

   ci = TColor::GetColor("#006600");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#006600");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("NBJetsCSVT_Top","Top","f");

   ci = TColor::GetColor("#3366cc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#3366cc");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("NBJetsCSVT_data","data","l");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("NBJetsCSVT_SMS","SMS","l");
   entry->SetLineColor(1);
   entry->SetLineStyle(3);
   entry->SetLineWidth(4);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
      tex = new TLatex(0.5837759,6763.483,"No PU RW No BTag SF");
   tex->SetLineWidth(2);
   tex->Draw();
   MT2_ratio_plotpad->Modified();
   MT2_ratioc_ratio->cd();
  
// ------------>Primitives in pad: MT2_ratio_ratiopad
   MT2_ratio_ratiopad = new TPad("MT2_ratio_ratiopad", "Pad containing the ratio",0,0.01863354,0.9967105,0.2189441);
   MT2_ratio_ratiopad->Draw();
   MT2_ratio_ratiopad->cd();
   MT2_ratio_ratiopad->Range(-0.6756336,-0.8571431,4.379105,2.214286);
   MT2_ratio_ratiopad->SetFillColor(0);
   MT2_ratio_ratiopad->SetBorderMode(0);
   MT2_ratio_ratiopad->SetBorderSize(2);
   MT2_ratio_ratiopad->SetLeftMargin(0.1336634);
   MT2_ratio_ratiopad->SetRightMargin(0.075);
   MT2_ratio_ratiopad->SetTopMargin(0.06976745);
   MT2_ratio_ratiopad->SetBottomMargin(0.2790698);
   MT2_ratio_ratiopad->SetFrameLineWidth(3);
   MT2_ratio_ratiopad->SetFrameBorderMode(0);
   MT2_ratio_ratiopad->SetFrameBorderSize(0);
   MT2_ratio_ratiopad->SetFrameLineWidth(3);
   MT2_ratio_ratiopad->SetFrameBorderMode(0);
   MT2_ratio_ratiopad->SetFrameBorderSize(0);
   
   TH1F *h1_copy = new TH1F("h1_copy","",4,0,4);
   h1_copy->SetBinContent(1,1);
   h1_copy->SetBinContent(2,1);
   h1_copy->SetBinContent(3,1);
   h1_copy->SetBinContent(4,1);
   h1_copy->SetBinError(1,0.0740823);
   h1_copy->SetBinError(2,0.07132595);
   h1_copy->SetBinError(3,0.06149714);
   h1_copy->SetBinError(4,0.248243);
   h1_copy->SetMinimum(0);
   h1_copy->SetMaximum(2);
   h1_copy->SetEntries(210.576);
   h1_copy->SetStats(0);
   h1_copy->SetFillColor(1);
   h1_copy->SetFillStyle(3001);
   h1_copy->SetLineColor(ci);
   h1_copy->SetLineWidth(2);
   h1_copy->SetMarkerColor(ci);
   h1_copy->GetXaxis()->SetTitle("NBJetsCSVT");
   h1_copy->GetXaxis()->SetNdivisions(505);
   h1_copy->GetXaxis()->SetLabelFont(42);
   h1_copy->GetXaxis()->SetLabelSize(0);
   h1_copy->GetXaxis()->SetTitleSize(0.2);
   h1_copy->GetXaxis()->SetTickLength(0.09);
   h1_copy->GetXaxis()->SetTitleOffset(0.5);
   h1_copy->GetXaxis()->SetTitleFont(42);
   h1_copy->GetYaxis()->SetTitle("Data / MC");
   h1_copy->GetYaxis()->SetNdivisions(509);
   h1_copy->GetYaxis()->SetLabelFont(42);
   h1_copy->GetYaxis()->SetLabelSize(0.19);
   h1_copy->GetYaxis()->SetTitleSize(0.18);
   h1_copy->GetYaxis()->SetTitleOffset(0.36);
   h1_copy->GetYaxis()->SetTitleFont(42);
   h1_copy->GetZaxis()->SetLabelFont(42);
   h1_copy->GetZaxis()->SetLabelSize(0.035);
   h1_copy->GetZaxis()->SetTitleSize(0.035);
   h1_copy->GetZaxis()->SetTitleFont(42);
   h1_copy->Draw("E2");
   
   TH1F *h2_copy__2 = new TH1F("h2_copy__2","",4,0,4);
   h2_copy__2->SetBinContent(1,1.169853);
   h2_copy__2->SetBinContent(2,1.103884);
   h2_copy__2->SetBinContent(3,0.9045112);
   h2_copy__2->SetBinContent(4,1.336297);
   h2_copy__2->SetBinError(1,0.06520752);
   h2_copy__2->SetBinError(2,0.0656394);
   h2_copy__2->SetBinError(3,0.06601925);
   h2_copy__2->SetBinError(4,0.3555964);
   h2_copy__2->SetMinimum(0.4);
   h2_copy__2->SetMaximum(3);
   h2_copy__2->SetEntries(146.2397);
   h2_copy__2->SetDirectory(0);
   h2_copy__2->SetStats(0);

   ci = TColor::GetColor("#ff0000");
   h2_copy__2->SetFillColor(ci);
   h2_copy__2->SetLineWidth(2);
   h2_copy__2->SetMarkerStyle(20);
   h2_copy__2->GetXaxis()->SetNdivisions(505);
   h2_copy__2->GetXaxis()->SetLabelFont(42);
   h2_copy__2->GetXaxis()->SetLabelSize(0.07);
   h2_copy__2->GetXaxis()->SetTitleSize(0.07);
   h2_copy__2->GetXaxis()->SetTitleOffset(1.1);
   h2_copy__2->GetXaxis()->SetTitleFont(42);
   h2_copy__2->GetYaxis()->SetNdivisions(505);
   h2_copy__2->GetYaxis()->SetLabelFont(42);
   h2_copy__2->GetYaxis()->SetLabelSize(0.07);
   h2_copy__2->GetYaxis()->SetTitleSize(0.07);
   h2_copy__2->GetYaxis()->SetTitleOffset(1.3);
   h2_copy__2->GetYaxis()->SetTitleFont(42);
   h2_copy__2->GetZaxis()->SetLabelFont(42);
   h2_copy__2->GetZaxis()->SetLabelSize(0.035);
   h2_copy__2->GetZaxis()->SetTitleSize(0.035);
   h2_copy__2->GetZaxis()->SetTitleFont(42);
   h2_copy__2->Draw("Esame");
   TLine *line = new TLine(0,1,4,1);
   line->SetLineStyle(7);
   line->SetLineWidth(2);
   line->Draw();
   
   TH1F *h1_copy__3 = new TH1F("h1_copy__3","",4,0,4);
   h1_copy__3->SetBinContent(1,1);
   h1_copy__3->SetBinContent(2,1);
   h1_copy__3->SetBinContent(3,1);
   h1_copy__3->SetBinContent(4,1);
   h1_copy__3->SetBinError(1,0.0740823);
   h1_copy__3->SetBinError(2,0.07132595);
   h1_copy__3->SetBinError(3,0.06149714);
   h1_copy__3->SetBinError(4,0.248243);
   h1_copy__3->SetMinimum(0);
   h1_copy__3->SetMaximum(2);
   h1_copy__3->SetEntries(210.576);
   h1_copy__3->SetDirectory(0);
   h1_copy__3->SetStats(0);
   h1_copy__3->SetFillColor(1);
   h1_copy__3->SetFillStyle(3001);
   h1_copy__3->SetLineColor(ci);
   h1_copy__3->SetLineWidth(2);
   h1_copy__3->SetMarkerColor(ci);
   h1_copy__3->GetXaxis()->SetTitle("NBJetsCSVT");
   h1_copy__3->GetXaxis()->SetNdivisions(505);
   h1_copy__3->GetXaxis()->SetLabelFont(42);
   h1_copy__3->GetXaxis()->SetLabelSize(0);
   h1_copy__3->GetXaxis()->SetTitleSize(0.2);
   h1_copy__3->GetXaxis()->SetTickLength(0.09);
   h1_copy__3->GetXaxis()->SetTitleOffset(0.5);
   h1_copy__3->GetXaxis()->SetTitleFont(42);
   h1_copy__3->GetYaxis()->SetTitle("Data / MC");
   h1_copy__3->GetYaxis()->SetNdivisions(509);
   h1_copy__3->GetYaxis()->SetLabelFont(42);
   h1_copy__3->GetYaxis()->SetLabelSize(0.19);
   h1_copy__3->GetYaxis()->SetTitleSize(0.18);
   h1_copy__3->GetYaxis()->SetTitleOffset(0.36);
   h1_copy__3->GetYaxis()->SetTitleFont(42);
   h1_copy__3->GetZaxis()->SetLabelFont(42);
   h1_copy__3->GetZaxis()->SetLabelSize(0.035);
   h1_copy__3->GetZaxis()->SetTitleSize(0.035);
   h1_copy__3->GetZaxis()->SetTitleFont(42);
   h1_copy__3->Draw("sameaxis");
   MT2_ratio_ratiopad->Modified();
   MT2_ratioc_ratio->cd();
   MT2_ratioc_ratio->Modified();
   MT2_ratioc_ratio->cd();
   MT2_ratioc_ratio->SetSelected(MT2_ratioc_ratio);
   MT2_ratioc_ratio->ToggleToolBar();
}
